"project_id": "343411"
"base_path": "."
"base_url": "https://api.crowdin.com"
"preserve_hierarchy": true

files: [
  {
    "source": "src/content/docs/en/**/*",
    "translation": "src/content/docs/%two_letters_code%/**/%original_file_name%",
  }
]
